export const UPDATE_USER_SETTINGS_REQUEST = "UPDATE_USER_SETTINGS_REQUEST"
export const UPDATE_USER_SETTINGS_SUCCESS = "UPDATE_USER_SETTINGS_SUCCESS"
export const UPDATE_USER_SETTINGS_FAILURE = "UPDATE_USER_SETTINGS_FAILURE"
